[package]
name = "cosmos-lock"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
calloop = { workspace = true }
calloop-wayland-source = { workspace = true }
smithay-client-toolkit = "0.21"
wayland-client = "0.31"
egui = { workspace = true }
pam = "0.8"
cosmos-uitk = { path = "../uitk" }
