[package]
name = "cosmos-greeter"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
egui = { workspace = true }
greetd_ipc = { version = "0.10", features = ["sync-codec"] }
cosmos-uitk = { path = "../uitk" }
image = { version = "0.25.1", default-features = false, features = ["png"] }
time = { version = "0.3", features = ["local-offset", "formatting"] }
