#!/usr/bin/env python3
"""Sample reference screenshots: colours (mean over a small box), luminance,
alpha-free contrast, and boxes scaled to a 1920px-wide screen.
Usage: python3 measure.py > measure.txt"""
import colorsys
from PIL import Image

# name: (file, screen_x0, screen_x1) — the screen's horizontal extent in the image.
SCREENS = {
    "ref-2": ("ref-2.png", 0, 361 * 1920 / 1920),  # cropped flyout, assume 1:1 at 100% scale
    "ref-3": ("ref-3.png", 122, 618),
    "ref-4": ("ref-4.png", 198, 1052),
    "ref-6": ("ref-6.png", 0, 739),
    "ref-7": ("ref-7.png", 0, 738),
}

SAMPLES = [
    ("ref-2", "flyout bg", (90, 140, 96, 146)),
    ("ref-2", "layout cell fill", (100, 80, 130, 120)),
    ("ref-2", "cell border", (84, 90, 86, 110)),
    ("ref-2", "browser bg behind", (10, 200, 40, 300)),
    ("ref-3", "pill fill", (330, 76, 420, 86)),
    ("ref-3", "wallpaper left of pill", (240, 76, 270, 86)),
    ("ref-3", "menubar", (300, 30, 400, 34)),
    ("ref-3", "dock", (360, 332, 380, 346)),
    ("ref-4", "menubar", (500, 50, 700, 60)),
    ("ref-4", "context menu fill", (640, 400, 700, 415)),
    ("ref-4", "doc under menu (left edge)", (590, 400, 605, 415)),
    ("ref-4", "window toolbar", (380, 104, 470, 124)),
    ("ref-4", "info pane fill", (890, 405, 1000, 420)),
    ("ref-4", "dock fill", (920, 568, 950, 592)),
    ("ref-4", "widget card", (215, 80, 230, 95)),
    ("ref-6", "wallpaper top-left", (0, 0, 40, 40)),
    ("ref-6", "wallpaper top-right", (700, 0, 739, 40)),
    ("ref-6", "wallpaper bottom-left", (0, 375, 40, 415)),
    ("ref-6", "wallpaper bottom-right", (700, 375, 739, 415)),
    ("ref-6", "search pill fill", (345, 10, 395, 22)),
    ("ref-6", "dock fill", (330, 393, 340, 410)),
    ("ref-7", "panel fill", (100, 70, 200, 80)),
    ("ref-7", "card fill (reminders)", (225, 140, 320, 145)),
    ("ref-7", "wallpaper", (600, 60, 700, 120)),
    ("ref-7", "accent button", (295, 220, 315, 225)),
    ("ref-7", "taskbar", (200, 400, 230, 410)),
]

BOXES = [
    ("ref-3", "Search or Ask pill", (284, 67, 456, 95)),
    ("ref-3", "menubar height", (122, 26, 618, 37)),
    ("ref-3", "dock", (148, 328, 592, 352)),
    ("ref-4", "menubar height", (198, 45, 1052, 65)),
    ("ref-4", "context menu", (612, 292, 718, 520)),
    ("ref-4", "context menu row pitch (Zoom In→Zoom Out)", (612, 330, 718, 344)),
    ("ref-4", "window", (234, 100, 842, 516)),
    ("ref-4", "window toolbar", (234, 100, 842, 128)),
    ("ref-4", "dock", (226, 562, 1024, 598)),
    ("ref-4", "dock icon", (234, 568, 256, 590)),
    ("ref-6", "search pill", (303, 6, 437, 27)),
    ("ref-6", "dock", (311, 391, 427, 413)),
    ("ref-6", "status text row", (600, 8, 739, 24)),
    ("ref-7", "widgets panel", (86, 27, 341, 388)),
    ("ref-7", "card (photos)", (98, 86, 210, 200)),
    ("ref-7", "perf ring", (224, 340, 244, 360)),
    ("ref-2", "flyout", (68, 37, 361, 343)),
    ("ref-2", "layout tile", (84, 55, 207, 133)),
    ("ref-2", "zone cell", (84, 55, 143, 133)),
]


def mean(img, box):
    px = list(img.crop(box).convert("RGB").getdata())
    n = len(px)
    return tuple(round(sum(p[i] for p in px) / n) for i in range(3))


def lum(c):
    def ch(v):
        v /= 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = (ch(v) for v in c)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


imgs = {k: Image.open(v[0]) for k, v in SCREENS.items()}
print("# Reference measurements (generated by measure.py)\n")
print("## Colours (mean RGB over box; hex; HSV hue°/sat/val; rel. luminance)")
for ref, label, box in SAMPLES:
    c = mean(imgs[ref], box)
    h, s, v = colorsys.rgb_to_hsv(*(x / 255 for x in c))
    print(f"{ref:6} {label:32} rgb{c!s:16} #{c[0]:02x}{c[1]:02x}{c[2]:02x}  "
          f"hue {h*360:5.0f} sat {s:.2f} val {v:.2f}  L {lum(c):.3f}")

print("\n## Boxes scaled to a 1920px-wide screen (approximate: hand-picked edges)")
for ref, label, (x0, y0, x1, y1) in BOXES:
    _, sx0, sx1 = SCREENS[ref]
    k = 1920 / (sx1 - sx0) if ref != "ref-2" else 1.0
    print(f"{ref:6} {label:44} {round((x1-x0)*k):5} x {round((y1-y0)*k):4} px  (scale {k:.2f})")
