[package]
name = "cosmos-monitor"
description = "CosmosOS system monitor"
edition = "2021"
license = "MIT"
version = "0.1.0"

[dependencies]
cosmos-theme = { path = "../../theme" }
cosmos-kit = { path = "../../kit" }
cosmos-uitk = { path = "../../uitk" }
egui = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bin]]
name = "cosmos-monitor"
path = "src/main.rs"
